title: My Portfolio
#logo: assets/img/headshot_circle.png
#description: text below image
show_downloads: true
remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0

- name: Page Name
  link: /page-1/
- name: Blog
  link: /blog/
  dropdown: 
    - name: Page 2
      link: /page-2/
